<nav x-data="{ open: false }" class="bg-white dark:bg-gray-800 border-b border-gray-100 dark:border-gray-700">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <div class="shrink-0 flex items-center"><a href="{{ route('dashboard') }}"><x-application-logo class="block h-9 w-auto fill-current text-gray-800" /></a></div>
                <div class="hidden space-x-8 sm:-my-px sm:ms-10 sm:flex">
                    
                    {{-- VISIBLE TO ALL --}}
                    <x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">{{ __('Dashboard') }}</x-nav-link>
                    <x-dropdown align="right" width="48"><x-slot name="trigger"><button class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-gray-500 bg-white hover:text-gray-700 focus:outline-none"><span>Sales</span><div class="ms-1"><svg class="fill-current h-4 w-4" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" /></svg></div></button></x-slot><x-slot name="content"><x-dropdown-link :href="route('sales.create')">{{ __('Sales') }}</x-dropdown-link><x-dropdown-link :href="route('sales.index')">{{ __('Sales Report') }}</x-dropdown-link><x-dropdown-link :href="route('customers.index')">{{ __('New Customers') }}</x-dropdown-link></x-slot></x-dropdown>

                    {{-- VISIBLE TO ADMINS & ACCOUNTS --}}
                    @if(Auth::user()->isAdmin() || Auth::user()->isAccounts())
                        <x-nav-link :href="route('vendors.index')" :active="request()->routeIs('vendors.index')">Vendor</x-nav-link>
                        <x-dropdown align="right" width="48"><x-slot name="trigger"><button class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-gray-500 bg-white hover:text-gray-700 focus:outline-none"><span>Accounts</span><div class="ms-1"><svg class="fill-current h-4 w-4" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" /></svg></div></button></x-slot><x-slot name="content"><x-dropdown-link :href="route('customer_accounts.index')">{{ __('Bill Received') }}</x-dropdown-link><x-dropdown-link :href="route('customer_advances.create')">{{ __('Customer Advance') }}</x-dropdown-link><x-dropdown-link :href="route('customer_ledgers.index')">{{ __('Customer Ledger') }}</x-dropdown-link><x-dropdown-link :href="route('vendor_accounts.index')">{{ __('Vendor Payment') }}</x-dropdown-link><x-dropdown-link :href="route('vendor_advances.create')">{{ __('Vendor Advance') }}</x-dropdown-link><x-dropdown-link :href="route('vendor_ledgers.index')">{{ __('Vendor Ledgure') }}</x-dropdown-link><x-dropdown-link :href="route('expenses.index')">{{ __('Expense') }}</x-dropdown-link></x-slot></x-dropdown>
                    @endif

                    {{-- VISIBLE TO ADMINS ONLY --}}
                    @if(Auth::user()->isAdmin())
                        <x-dropdown align="right" width="48"><x-slot name="trigger"><button class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-gray-500 bg-white hover:text-gray-700 focus:outline-none"><span>Store</span><div class="ms-1"><svg class="fill-current h-4 w-4" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" /></svg></div></button></x-slot><x-slot name="content"><x-dropdown-link :href="route('stocks.index')">{{ __('Current Stocks') }}</x-dropdown-link><x-dropdown-link :href="route('purchases.create')">{{ __('Purchase') }}</x-dropdown-link><x-dropdown-link :href="route('purchases.index')">{{ __('Purchase History') }}</x-dropdown-link></x-slot></x-dropdown>
                        <x-dropdown align="right" width="48"><x-slot name="trigger"><button class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-gray-500 bg-white hover:text-gray-700 focus:outline-none"><span>System Setup</span><div class="ms-1"><svg class="fill-current h-4 w-4" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" /></svg></div></button></x-slot><x-slot name="content"><x-dropdown-link :href="route('categories.index')">{{ __('Catagory Setup') }}</x-dropdown-link><x-dropdown-link :href="route('product_types.index')">{{ __('Product Type Setup') }}</x-dropdown-link><x-dropdown-link :href="route('brands.index')">{{ __('Brand Setup') }}</x-dropdown-link><x-dropdown-link :href="route('products.index')">{{ __('Item Setup') }}</x-dropdown-link></x-slot></x-dropdown>
                        <x-dropdown align="right" width="48"><x-slot name="trigger"><button class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-gray-500 bg-white hover:text-gray-700 focus:outline-none"><span>Employee</span><div class="ms-1"><svg class="fill-current h-4 w-4" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" /></svg></div></button></x-slot><x-slot name="content"><x-dropdown-link :href="route('employees.index')">{{ __('New Employee') }}</x-dropdown-link><x-dropdown-link :href="route('users.index')">{{ __('User Management') }}</x-dropdown-link></x-slot></x-dropdown>
                    @endif
                </div>
            </div>
            <div class="hidden sm:flex sm:items-center sm:ms-6">
                <x-dropdown align="right" width="48"><x-slot name="trigger"><button class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-gray-500 bg-white hover:text-gray-700 focus:outline-none"><div>{{ Auth::user()->name }} ({{ Auth::user()->role }})</div><div class="ms-1"><svg class="fill-current h-4 w-4" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" /></svg></div></button></x-slot><x-slot name="content"><x-dropdown-link :href="route('profile.edit')">{{ __('Profile') }}</x-dropdown-link><form method="POST" action="{{ route('logout') }}">@csrf<x-dropdown-link :href="route('logout')" onclick="event.preventDefault(); this.closest('form').submit();">{{ __('Log Out') }}</x-dropdown-link></form></x-slot></x-dropdown>
            </div>
            <div class="-me-2 flex items-center sm:hidden"><button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500"><svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24"><path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" /><path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" /></svg></button></div>
        </div>
    </div>
</nav>